from sqlalchemy import Column, String, DateTime, Integer, Numeric, Text, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from app.db.session import Base
import uuid
from datetime import datetime

class ShipmentRequest(Base):
    __tablename__ = "shipment_requests"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    unique_id = Column(String, unique=True, index=True) # e.g. SHP-00001
    
    # Link to User (String ID)
    user_id = Column(String, ForeignKey('users.id'))
    user = relationship("User", back_populates="shipment_requests")
    
    origin_city = Column(String, nullable=False)
    origin_country = Column(String(2), nullable=False)
    dest_city = Column(String, nullable=False)
    dest_country = Column(String(2), nullable=False)
    
    cargo_type = Column(String, nullable=False) # 'FCL', 'LCL', 'Air'
    weight_kg = Column(Numeric, nullable=True)
    volume_cbm = Column(Numeric, nullable=True)
    cargo_value = Column(Numeric, nullable=True)
    
    incoterms = Column(String, nullable=True)
    notes = Column(Text, nullable=True)
    
    # Stores the full raw form data for AI parsing fallback or reference
    raw_input = Column(Text, nullable=True)
    
    # Stores the AI-cleaned RFQ text (generated by n8n)
    formatted_rfq = Column(Text, nullable=True)
    
    status = Column(String, default='open') # 'open', 'closed', 'expired'
    quotes_count = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)


class MarketplaceQuote(Base):
    __tablename__ = "marketplace_quotes"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    shipment_id = Column(String, ForeignKey('shipment_requests.id'))
    forwarder_id = Column(String, ForeignKey('forwarders.id'))
    
    price = Column(Numeric, nullable=False)
    currency = Column(String, default='USD')
    transit_days = Column(Integer, nullable=True)
    mode = Column(String, nullable=True) # 'Sea', 'Air'
    terms = Column(Text, nullable=True)
    
    validity_days = Column(Integer, default=7)
    notes = Column(Text, nullable=True)
    
    # The raw email reply body (for reference)
    raw_reply = Column(Text, nullable=True)
    
    # 1, 2, or 3 (First 3 Wins)
    position = Column(Integer, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)


class NotificationLog(Base):
    """
    Tracks which forwarders were notified about which shipment.
    Crucial for implementing the 'Reminders' workflow without spamming.
    """
    __tablename__ = "notification_log"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    shipment_id = Column(String, ForeignKey('shipment_requests.id'))
    forwarder_id = Column(String, ForeignKey('forwarders.id'))
    
    email_sent = Column(Boolean, default=False)
    replied = Column(Boolean, default=False)
    
    reminder_count = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
