"""add_company_name

Revision ID: 1d69b4e61a19
Revises: 3c5a5a9effa2
Create Date: 2026-02-10 01:13:43.051678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d69b4e61a19'
down_revision: Union[str, None] = '3c5a5a9effa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quotes_destination'), 'quotes', ['destination'], unique=False)
    op.create_index(op.f('ix_quotes_origin'), 'quotes', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_origin'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_destination'), table_name='quotes')
    # ### end Alembic commands ###
