"""Add Marketplace Expansion Tables v2

Revision ID: 535805abcaeb
Revises: 6f567753484a
Create Date: 2026-02-17 23:57:35.812419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535805abcaeb'
down_revision: Union[str, None] = '6f567753484a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shipment_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('origin_city', sa.String(), nullable=False),
    sa.Column('origin_country', sa.String(length=2), nullable=False),
    sa.Column('dest_city', sa.String(), nullable=False),
    sa.Column('dest_country', sa.String(length=2), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(), nullable=True),
    sa.Column('cargo_value', sa.Numeric(), nullable=True),
    sa.Column('incoterms', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('formatted_rfq', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quotes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_requests_unique_id'), 'shipment_requests', ['unique_id'], unique=True)
    op.create_table('marketplace_quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('forwarder_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_reply', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('forwarder_id', sa.String(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('replied', sa.Boolean(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bookings', 'booking_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('bookings_booking_reference_key'), 'bookings', type_='unique')
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='failed_login_attempts::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.create_unique_constraint(op.f('bookings_booking_reference_key'), 'bookings', ['booking_reference'], postgresql_nulls_not_distinct=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookings', 'booking_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('notification_log')
    op.drop_table('marketplace_quotes')
    op.drop_index(op.f('ix_shipment_requests_unique_id'), table_name='shipment_requests')
    op.drop_table('shipment_requests')
    op.drop_table('forwarders')
    # ### end Alembic commands ###
