"""align_world_class_schema

Revision ID: 6f567753484a
Revises: c37983e3cd76
Create Date: 2026-02-11 15:49:05.428634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f567753484a'
down_revision: Union[str, None] = 'c37983e3cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create UserActivity Table IF NOT EXISTS
    op.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS user_activities (
            id VARCHAR NOT NULL, 
            user_id VARCHAR, 
            action VARCHAR NOT NULL, 
            entity_type VARCHAR, 
            entity_id VARCHAR, 
            ip_address VARCHAR, 
            user_agent VARCHAR, 
            extra_data TEXT, 
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
            PRIMARY KEY (id), 
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """))
    
    # Add Missing Sovereign Columns to Users (Idempotent)
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR"))
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR"))
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS preferences VARCHAR"))
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts VARCHAR DEFAULT '0'"))
    op.execute(sa.text("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
