"""add_bookings_table

Revision ID: 775f663c0b94
Revises: 063ba93ea51b
Create Date: 2026-03-20 08:47:09.253389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775f663c0b94'
down_revision: Union[str, None] = '063ba93ea51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('user_sovereign_id', sa.String(length=100), nullable=False),
    sa.Column('carrier_name', sa.String(length=200), nullable=False),
    sa.Column('vessel_name', sa.String(length=200), nullable=True),
    sa.Column('origin_locode', sa.String(length=20), nullable=False),
    sa.Column('destination_locode', sa.String(length=20), nullable=False),
    sa.Column('container_type', sa.String(length=20), nullable=False),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('marketplace_request_id', sa.String(length=100), nullable=True),
    sa.Column('quote_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_user_status', 'bookings', ['user_sovereign_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_confirmed_at'), 'bookings', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_marketplace_request_id'), 'bookings', ['marketplace_request_id'], unique=False)
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_sovereign_id'), 'bookings', ['user_sovereign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_sovereign_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_marketplace_request_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_confirmed_at'), table_name='bookings')
    op.drop_index('idx_booking_user_status', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
