"""sync_user_model_fields

Revision ID: d2241d744c54
Revises: 535805abcaeb
Create Date: 2026-02-18 13:11:09.394364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2241d744c54'
down_revision: Union[str, None] = '535805abcaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarders', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('document_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'forwarders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forwarders', type_='foreignkey')
    op.drop_column('forwarders', 'document_url')
    op.drop_column('forwarders', 'tax_id')
    op.drop_column('forwarders', 'user_id')
    # ### end Alembic commands ###
