"""final_schema_sync

Revision ID: f4737e8d91c1
Revises: d2241d744c54
Create Date: 2026-02-24 17:45:16.877360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4737e8d91c1'
down_revision: Union[str, None] = 'd2241d744c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_marketplace_bids_forwarder_id'), 'marketplace_bids', ['forwarder_id'], unique=False)
    op.create_index(op.f('ix_marketplace_bids_request_id'), 'marketplace_bids', ['request_id'], unique=False)
    op.create_index(op.f('ix_marketplace_requests_sovereign_id'), 'marketplace_requests', ['sovereign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_requests_sovereign_id'), table_name='marketplace_requests')
    op.drop_index(op.f('ix_marketplace_bids_request_id'), table_name='marketplace_bids')
    op.drop_index(op.f('ix_marketplace_bids_forwarder_id'), table_name='marketplace_bids')
    # ### end Alembic commands ###
