"""n8n_architecture_sync

Revision ID: fe3d3e683307
Revises: f4737e8d91c1
Create Date: 2026-02-26 00:24:44.983570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe3d3e683307'
down_revision: Union[str, None] = 'f4737e8d91c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('n8n_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('total_quotations', sa.Integer(), nullable=True),
    sa.Column('requests_closed', sa.Integer(), nullable=True),
    sa.Column('avg_quotes_per_request', sa.Float(), nullable=True),
    sa.Column('stale_requests_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_analytics_date'), 'n8n_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_n8n_analytics_id'), 'n8n_analytics', ['id'], unique=False)
    op.create_table('n8n_broadcast_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('forwarder_id', sa.String(), nullable=True),
    sa.Column('forwarder_company', sa.String(), nullable=True),
    sa.Column('email_sent', sa.String(), nullable=True),
    sa.Column('whatsapp_sent', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_broadcast_logs_forwarder_id'), 'n8n_broadcast_logs', ['forwarder_id'], unique=False)
    op.create_index(op.f('ix_n8n_broadcast_logs_id'), 'n8n_broadcast_logs', ['id'], unique=False)
    op.create_index(op.f('ix_n8n_broadcast_logs_log_id'), 'n8n_broadcast_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_n8n_broadcast_logs_request_id'), 'n8n_broadcast_logs', ['request_id'], unique=False)
    op.create_table('n8n_events_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_events_logs_event_id'), 'n8n_events_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_n8n_events_logs_id'), 'n8n_events_logs', ['id'], unique=False)
    op.create_index(op.f('ix_n8n_events_logs_request_id'), 'n8n_events_logs', ['request_id'], unique=False)
    op.create_table('n8n_rejected_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_n8n_rejected_attempts_id'), 'n8n_rejected_attempts', ['id'], unique=False)
    op.add_column('forwarders', sa.Column('contact_person', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('specializations', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('routes', sa.String(), nullable=True))
    op.add_column('forwarders', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('forwarders', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.drop_column('forwarders', 'stripe_customer_id')
    op.add_column('marketplace_bids', sa.Column('quotation_id', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('forwarder_company', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('carrier', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('service_type', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('surcharges', sa.JSON(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('raw_email', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('status', sa.String(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('marketplace_bids', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_marketplace_bids_quotation_id'), 'marketplace_bids', ['quotation_id'], unique=True)
    op.drop_column('marketplace_bids', 'position')
    op.drop_column('marketplace_bids', 'vendor_logo')
    op.drop_column('marketplace_bids', 'raw_reply')
    op.drop_column('marketplace_bids', 'vendor_country')
    op.drop_column('marketplace_bids', 'vendor_name')
    op.drop_column('marketplace_bids', 'created_at')
    op.drop_column('marketplace_bids', 'mode')
    op.drop_column('marketplace_bids', 'price')
    op.drop_column('marketplace_bids', 'terms')
    op.add_column('marketplace_requests', sa.Column('user_sovereign_id', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('dimensions', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('special_requirements', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('quotation_count', sa.Integer(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('marketplace_requests', sa.Column('closed_reason', sa.String(), nullable=True))
    op.drop_index(op.f('ix_marketplace_requests_sovereign_id'), table_name='marketplace_requests')
    op.drop_index(op.f('ix_marketplace_requests_user_id'), table_name='marketplace_requests')
    op.create_index(op.f('ix_marketplace_requests_user_sovereign_id'), 'marketplace_requests', ['user_sovereign_id'], unique=False)
    op.drop_column('marketplace_requests', 'sovereign_id')
    op.drop_column('marketplace_requests', 'cargo_value')
    op.drop_column('marketplace_requests', 'user_id')
    op.drop_column('marketplace_requests', 'cargo_details')
    op.drop_column('marketplace_requests', 'origin_country')
    op.drop_column('marketplace_requests', 'dest_city')
    op.drop_column('marketplace_requests', 'origin_city')
    op.drop_column('marketplace_requests', 'dest_country')
    op.drop_column('marketplace_requests', 'volume_cbm')
    op.drop_column('marketplace_requests', 'created_at')
    op.drop_column('marketplace_requests', 'notes')
    op.drop_column('marketplace_requests', 'quotes_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_requests', sa.Column('quotes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('volume_cbm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('dest_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('origin_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('dest_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('origin_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('cargo_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('cargo_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('marketplace_requests', sa.Column('sovereign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_marketplace_requests_user_sovereign_id'), table_name='marketplace_requests')
    op.create_index(op.f('ix_marketplace_requests_user_id'), 'marketplace_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_marketplace_requests_sovereign_id'), 'marketplace_requests', ['sovereign_id'], unique=False)
    op.drop_column('marketplace_requests', 'closed_reason')
    op.drop_column('marketplace_requests', 'submitted_at')
    op.drop_column('marketplace_requests', 'quotation_count')
    op.drop_column('marketplace_requests', 'currency')
    op.drop_column('marketplace_requests', 'special_requirements')
    op.drop_column('marketplace_requests', 'dimensions')
    op.drop_column('marketplace_requests', 'destination')
    op.drop_column('marketplace_requests', 'origin')
    op.drop_column('marketplace_requests', 'user_sovereign_id')
    op.add_column('marketplace_bids', sa.Column('terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('vendor_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('raw_reply', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('vendor_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplace_bids', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_marketplace_bids_quotation_id'), table_name='marketplace_bids')
    op.drop_column('marketplace_bids', 'expires_at')
    op.drop_column('marketplace_bids', 'received_at')
    op.drop_column('marketplace_bids', 'status')
    op.drop_column('marketplace_bids', 'raw_email')
    op.drop_column('marketplace_bids', 'ai_summary')
    op.drop_column('marketplace_bids', 'payment_terms')
    op.drop_column('marketplace_bids', 'surcharges')
    op.drop_column('marketplace_bids', 'service_type')
    op.drop_column('marketplace_bids', 'carrier')
    op.drop_column('marketplace_bids', 'total_price')
    op.drop_column('marketplace_bids', 'forwarder_company')
    op.drop_column('marketplace_bids', 'quotation_id')
    op.add_column('forwarders', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('forwarders', 'activated_at')
    op.drop_column('forwarders', 'registered_at')
    op.drop_column('forwarders', 'routes')
    op.drop_column('forwarders', 'specializations')
    op.drop_column('forwarders', 'whatsapp')
    op.drop_column('forwarders', 'contact_person')
    op.drop_index(op.f('ix_n8n_rejected_attempts_id'), table_name='n8n_rejected_attempts')
    op.drop_table('n8n_rejected_attempts')
    op.drop_index(op.f('ix_n8n_events_logs_request_id'), table_name='n8n_events_logs')
    op.drop_index(op.f('ix_n8n_events_logs_id'), table_name='n8n_events_logs')
    op.drop_index(op.f('ix_n8n_events_logs_event_id'), table_name='n8n_events_logs')
    op.drop_table('n8n_events_logs')
    op.drop_index(op.f('ix_n8n_broadcast_logs_request_id'), table_name='n8n_broadcast_logs')
    op.drop_index(op.f('ix_n8n_broadcast_logs_log_id'), table_name='n8n_broadcast_logs')
    op.drop_index(op.f('ix_n8n_broadcast_logs_id'), table_name='n8n_broadcast_logs')
    op.drop_index(op.f('ix_n8n_broadcast_logs_forwarder_id'), table_name='n8n_broadcast_logs')
    op.drop_table('n8n_broadcast_logs')
    op.drop_index(op.f('ix_n8n_analytics_id'), table_name='n8n_analytics')
    op.drop_index(op.f('ix_n8n_analytics_date'), table_name='n8n_analytics')
    op.drop_table('n8n_analytics')
    # ### end Alembic commands ###
